name: Build Project

on:
  workflow_dispatch: 
  push:
    branches: # aAAA
      - main         
  pull_request:      

jobs:
  build-and-package:
    runs-on: self-hosted 

    steps:
      - name: download reppoo
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: get lfs cache
        run: |
            git lfs install
            git lfs pull

      - name: start packaging the project
        env:
          UE-LocalDataCachePath: "D:\\UE_DDC"
        run: |
          & "D:\Epic Games\UE_5.7\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="${{ github.workspace }}\MI498_UEProject.uproject" -noP4 -platform=Win64 -clientconfig=Development -build -cook -stage -package -nullrhi -iterate -AdditionalCookerOptions="-cookprocesscount=4"